export const portfolioPageQuery = `*[_id == "portfolioPage"][0]{
  _id,
  tabs,
  hero,
  profileIntro{
    label,
    heading,
    body,
    buttonSkills,
    buttonNext,
    profileAvatar{
      asset->{url}
    }
  },
  skills,
  projectsSection,
  contact,
  musicPlayer,
  "projects": projects[]->{
    _id,
    title,
    meta,
    categoryYear,
    description,
    metadata,
    listHeaderLabel,
    results,
    cardGradient,
    cardEmoji,
    thumbnail{
      asset->{url}
    }
  }
}`;

export const projectByIdQuery = `*[_type == "project" && _id == $id][0]{
  _id,
  title,
  meta,
  categoryYear,
  description,
  metadata,
  listHeaderLabel,
  results,
  cardGradient,
  cardEmoji,
  thumbnail{
    asset->{url}
  }
}`;
